package dev.homelabmonitor.monitor;

public enum MonitorChange {
	MONITOR_CREATED,
	MONITOR_UPDATED,
	MONITOR_DELETED,
	CHECK_COMPLETED,
	STATUS_CHANGED,
	INCIDENT_OPENED,
	INCIDENT_RESOLVED,
	FRESHNESS_EXPIRED
}
