package dev.homelabmonitor.monitor;

public enum StateChangeReason {
	MONITOR_CREATED,
	CONFIGURATION_CHANGED,
	MONITORING_PAUSED,
	MONITORING_RESUMED,
	CHECK_SUCCEEDED,
	LATENCY_THRESHOLD_EXCEEDED,
	FAILURE_THRESHOLD_REACHED,
	RECOVERY_THRESHOLD_REACHED,
	OBSERVATION_STALE
}
